import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { IBM_Plex_Sans } from "next/font/google";

import { Providers } from "./Providers";
import SessionGuard from '@/components/SessionGuard'
import { Sidebar } from '@/components/Sidebar';

import "./globals.css";

const font = IBM_Plex_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <SessionGuard>
            <div className="flex flex-1">
              <Sidebar />
              <div className="flex-1">
                <header className="bg-white">
                  <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
                    {/* <div className="flex lg:flex-1">
                      <Link href={'/'}>
                        <span className="text-xl font-medium text-primary-100">Aarogya aarohon</span>
                      </Link>
                    </div> */}
                    {/* <div className="hidden sm:ml-6 sm:block">
                      <div className="flex space-x-4">
                        <Link href="/users" className="text-gray-300 hover:text-primary-100 rounded-md px-3 py-2 text-sm font-medium">Users</Link>
                        <Link href="/user-groups" className="text-gray-300 hover:text-primary-100 rounded-md px-3 py-2 text-sm font-medium">User groups</Link>
                        <Link href="/user-roles" className="text-gray-300 hover:text-primary-100 rounded-md px-3 py-2 text-sm font-medium">User roles</Link>
                        <Link href="/tasks" className="text-gray-300 hover:text-primary-100 rounded-md px-3 py-2 text-sm font-medium">Tasks</Link>
                      </div>
                    </div> */}
                    <div className="flex flex-1 justify-end">
                      <Image
                        height={28}
                        width={28}
                        className={`h-[28px] w-[28px] rounded-full object-cover`}
                        src={"https://tailwindui.com/img/logos/mark.svg"}
                        alt={"Profile"}
                      />
                    </div>
                  </nav>
                  <hr className="sm:hidden" />
                  <div className="sm:hidden" >
                    <div className="space-y-1 px-2 pb-3 pt-2">
                      <Link href="/users" className="text-gray-300 rounded-md px-3 py-2 text-sm font-medium">Users</Link>
                      <Link href="/user-roles" className="text-gray-300 hover:text-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">User roles</Link>
                      <Link href="/user-groups" className="text-gray-300 hover:text-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">User groups</Link>
                      <Link href="/tasks" className="text-gray-300 hover:text-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Tasks</Link>
                    </div>
                  </div>
                </header>
                <hr />
                {children}
              </div>
            </div>
          </SessionGuard>
        </Providers>
      </body>
    </html>
  );
}
