name: Build and Deploy to Staging

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "::set-output name=short_commit_id::$(git rev-parse --short HEAD)"

      - name: Print Short Commit ID
        run: echo "${{ steps.vars.outputs.short_commit_id }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: iisc/arogyam-dashboard:${{steps.vars.outputs.short_commit_id}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_FHIR_API_BASE_URL=https://staging.arogyam-midas.iisc.ac.in/fhir
            NEXT_PUBLIC_KEYCLOAK_URL=https://staging.arogyam-midas.iisc.ac.in/auth
            NEXT_PUBLIC_KEYCLOAK_REALM=arogyam
